


development:
    adapter: postgresql
    encoding: UTF8
    database: pin_development
    pool: 5
    username: lotterymac
    password: zhongwen

test:
  adapter: postgresql
  encoding: UTF8
  database: pin_test
  pool: 5
  username: lotterymac
  password: zhongwen
